"""
S1AP Information Element (IE) Definitions
Complete mapping of S1AP IEs according to 3GPP TS 36.413
"""

from typing import Dict, Any, Optional
from enum import Enum

class IEType(Enum):
    """IE Data Types"""
    INTEGER = "INTEGER"
    ENUMERATED = "ENUMERATED"
    BIT_STRING = "BIT STRING"
    OCTET_STRING = "OCTET STRING"
    SEQUENCE = "SEQUENCE"
    SEQUENCE_OF = "SEQUENCE OF"
    CHOICE = "CHOICE"
    BOOLEAN = "BOOLEAN"

# Complete S1AP IE Dictionary (3GPP TS 36.413 V18.3.0)
S1AP_IES = {
    0: {"name": "MME-UE-S1AP-ID", "type": IEType.INTEGER, "range": (0, 4294967295), "description": "MME UE S1AP ID"},
    1: {"name": "HandoverType", "type": IEType.ENUMERATED, "values": {"intralte": 0, "ltetoutran": 1, "ltetogeran": 2, "utrantolte": 3, "gerantolte": 4}, "description": "Handover type"},
    2: {"name": "Cause", "type": IEType.CHOICE, "choices": ["radioNetwork", "transport", "nas", "protocol", "misc"], "description": "Cause"},
    3: {"name": "SourceID", "type": IEType.CHOICE, "choices": ["sourceENB-ID", "sourceRNC-ID"], "description": "Source ID"},
    4: {"name": "TargetID", "type": IEType.CHOICE, "choices": ["targetENB-ID", "targetRNC-ID", "cGI"], "description": "Target ID"},
    5: {"name": "Unknown-5", "type": IEType.OCTET_STRING, "description": "WS extension"},
    6: {"name": "Unknown-6", "type": IEType.OCTET_STRING, "description": "WS extension"},
    7: {"name": "Unknown-7", "type": IEType.OCTET_STRING, "description": "WS extension"},
    8: {"name": "eNB-UE-S1AP-ID", "type": IEType.INTEGER, "range": (0, 16777215), "description": "eNB UE S1AP ID"},
    9: {"name": "Unknown-9", "type": IEType.OCTET_STRING, "description": "WS extension"},
    10: {"name": "Unknown-10", "type": IEType.OCTET_STRING, "description": "WS extension"},
    11: {"name": "Unknown-11", "type": IEType.OCTET_STRING, "description": "WS extension"},
    12: {"name": "E-RABSubjecttoDataForwardingList", "type": IEType.SEQUENCE_OF, "description": "E-RAB subject to data forwarding list"},
    13: {"name": "E-RABtoReleaseListHOCmd", "type": IEType.SEQUENCE_OF, "description": "E-RAB to release list HO command"},
    14: {"name": "E-RABDataForwardingItem", "type": IEType.SEQUENCE, "description": "E-RAB data forwarding item"},
    15: {"name": "E-RABReleaseItemBearerRelComp", "type": IEType.SEQUENCE, "description": "E-RAB release item bearer release complete"},
    16: {"name": "E-RABToBeSetupListBearerSUReq", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be setup list bearer setup request"},
    17: {"name": "E-RABToBeSetupItemBearerSUReq", "type": IEType.SEQUENCE, "description": "E-RAB to be setup item bearer setup request"},
    18: {"name": "E-RABAdmittedList", "type": IEType.SEQUENCE_OF, "description": "E-RAB admitted list"},
    19: {"name": "E-RABFailedToSetupListHOReqAck", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to setup list HO request ack"},
    20: {"name": "E-RABAdmittedItem", "type": IEType.SEQUENCE, "description": "E-RAB admitted item"},
    21: {"name": "E-RABFailedtoSetupItemHOReqAck", "type": IEType.SEQUENCE, "description": "E-RAB failed to setup item HO request ack"},
    22: {"name": "E-RABToBeSwitchedDLList", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be switched DL list"},
    23: {"name": "E-RABToBeSwitchedDLItem", "type": IEType.SEQUENCE, "description": "E-RAB to be switched DL item"},
    24: {"name": "E-RABToBeSetupListCtxtSUReq", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be setup list context setup request"},
    25: {"name": "TraceActivation", "type": IEType.SEQUENCE, "description": "Trace activation"},
    26: {"name": "NAS-PDU", "type": IEType.OCTET_STRING, "description": "NAS PDU"},
    27: {"name": "E-RABToBeSetupItemHOReq", "type": IEType.SEQUENCE, "description": "E-RAB to be setup item HO request"},
    28: {"name": "E-RABSetupListBearerSURes", "type": IEType.SEQUENCE_OF, "description": "E-RAB setup list bearer setup response"},
    29: {"name": "E-RABFailedToSetupListBearerSURes", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to setup list bearer setup response"},
    30: {"name": "E-RABToBeModifiedListBearerModReq", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be modified list bearer modification request"},
    31: {"name": "E-RABModifyListBearerModRes", "type": IEType.SEQUENCE_OF, "description": "E-RAB modify list bearer modification response"},
    32: {"name": "E-RABFailedToModifyList", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to modify list"},
    33: {"name": "E-RABToBeReleasedList", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be released list"},
    34: {"name": "E-RABFailedToReleaseList", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to release list"},
    35: {"name": "E-RABItem", "type": IEType.SEQUENCE, "description": "E-RAB item"},
    36: {"name": "E-RABToBeModifiedItemBearerModReq", "type": IEType.SEQUENCE, "description": "E-RAB to be modified item bearer modification request"},
    37: {"name": "E-RABModifyItemBearerModRes", "type": IEType.SEQUENCE, "description": "E-RAB modify item bearer modification response"},
    38: {"name": "E-RABReleaseItem", "type": IEType.SEQUENCE, "description": "E-RAB release item"},
    39: {"name": "E-RABSetupItemBearerSURes", "type": IEType.SEQUENCE, "description": "E-RAB setup item bearer setup response"},
    40: {"name": "SecurityContext", "type": IEType.SEQUENCE, "description": "Security context"},
    41: {"name": "HandoverRestrictionList", "type": IEType.SEQUENCE, "description": "Handover restriction list"},
    42: {"name": "Unknown-42", "type": IEType.OCTET_STRING, "description": "WS extension"},
    43: {"name": "UEPagingID", "type": IEType.CHOICE, "choices": ["s-TMSI", "iMSI"], "description": "UE paging ID"},
    44: {"name": "pagingDRX", "type": IEType.ENUMERATED, "values": {"v32": 0, "v64": 1, "v128": 2, "v256": 3}, "description": "Paging DRX"},
    45: {"name": "Unknown-45", "type": IEType.OCTET_STRING, "description": "WS extension"},
    46: {"name": "TAIList", "type": IEType.SEQUENCE_OF, "description": "TAI list"},
    47: {"name": "TAIItem", "type": IEType.SEQUENCE, "description": "TAI item"},
    48: {"name": "E-RABFailedToSetupListCtxtSURes", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to setup list context setup response"},
    49: {"name": "E-RABReleaseItemHOCmd", "type": IEType.SEQUENCE, "description": "E-RAB release item HO command"},
    50: {"name": "E-RABSetupItemCtxtSURes", "type": IEType.SEQUENCE, "description": "E-RAB setup item context setup response"},
    51: {"name": "E-RABSetupListCtxtSURes", "type": IEType.SEQUENCE_OF, "description": "E-RAB setup list context setup response"},
    52: {"name": "E-RABToBeSetupItemCtxtSUReq", "type": IEType.SEQUENCE, "description": "E-RAB to be setup item context setup request"},
    53: {"name": "E-RABToBeSetupListHOReq", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be setup list HO request"},
    54: {"name": "Unknown-54", "type": IEType.OCTET_STRING, "description": "WS extension"},
    55: {"name": "GERANtoLTEHOInformationRes", "type": IEType.SEQUENCE, "description": "GERAN to LTE HO information response"},
    56: {"name": "Unknown-56", "type": IEType.OCTET_STRING, "description": "WS extension"},
    57: {"name": "UTRANtoLTEHOInformationRes", "type": IEType.SEQUENCE, "description": "UTRAN to LTE HO information response"},
    58: {"name": "CriticalityDiagnostics", "type": IEType.SEQUENCE, "description": "Criticality diagnostics"},
    59: {"name": "Global-ENB-ID", "type": IEType.SEQUENCE, "description": "Global eNB ID"},
    60: {"name": "eNBname", "type": IEType.OCTET_STRING, "description": "eNB name"},
    61: {"name": "MMEname", "type": IEType.OCTET_STRING, "description": "MME name"},
    62: {"name": "Unknown-62", "type": IEType.OCTET_STRING, "description": "WS extension"},
    63: {"name": "ServedPLMNs", "type": IEType.SEQUENCE_OF, "description": "Served PLMNs"},
    64: {"name": "SupportedTAs", "type": IEType.SEQUENCE_OF, "description": "Supported TAs"},
    65: {"name": "TimeToWait", "type": IEType.ENUMERATED, "values": {"v1s": 0, "v2s": 1, "v5s": 2, "v10s": 3, "v20s": 4, "v60s": 5}, "description": "Time to wait"},
    66: {"name": "uEaggregateMaximumBitrate", "type": IEType.SEQUENCE, "description": "UE aggregate maximum bitrate"},
    67: {"name": "TAI", "type": IEType.SEQUENCE, "description": "TAI"},
    68: {"name": "Unknown-68", "type": IEType.OCTET_STRING, "description": "WS extension"},
    69: {"name": "E-RABReleaseListBearerRelComp", "type": IEType.SEQUENCE_OF, "description": "E-RAB release list bearer release complete"},
    70: {"name": "cdma2000PDU", "type": IEType.OCTET_STRING, "description": "CDMA2000 PDU"},
    71: {"name": "cdma2000RATType", "type": IEType.ENUMERATED, "values": {"hRPD": 0, "oneXRTT": 1}, "description": "CDMA2000 RAT type"},
    72: {"name": "cdma2000SectorID", "type": IEType.OCTET_STRING, "description": "CDMA2000 sector ID"},
    73: {"name": "SecurityKey", "type": IEType.BIT_STRING, "size": 256, "description": "Security key"},
    74: {"name": "UERadioCapability", "type": IEType.OCTET_STRING, "description": "UE radio capability"},
    75: {"name": "GUMMEI-ID", "type": IEType.SEQUENCE, "description": "GUMMEI ID"},
    76: {"name": "Unknown-76", "type": IEType.OCTET_STRING, "description": "WS extension"},
    77: {"name": "Unknown-77", "type": IEType.OCTET_STRING, "description": "WS extension"},
    78: {"name": "E-RABInformationListItem", "type": IEType.SEQUENCE, "description": "E-RAB information list item"},
    79: {"name": "Direct-Forwarding-Path-Availability", "type": IEType.ENUMERATED, "values": {"directPathAvailable": 0}, "description": "Direct forwarding path availability"},
    80: {"name": "UEIdentityIndexValue", "type": IEType.BIT_STRING, "size": 10, "description": "UE identity index value"},
    81: {"name": "Unknown-81", "type": IEType.OCTET_STRING, "description": "WS extension"},
    82: {"name": "Unknown-82", "type": IEType.OCTET_STRING, "description": "WS extension"},
    83: {"name": "cdma2000HOStatus", "type": IEType.ENUMERATED, "values": {"hOSuccess": 0, "hOFailure": 1}, "description": "CDMA2000 HO status"},
    84: {"name": "cdma2000HORequiredIndication", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "CDMA2000 HO required indication"},
    85: {"name": "Unknown-85", "type": IEType.OCTET_STRING, "description": "WS extension"},
    86: {"name": "E-UTRAN-Trace-ID", "type": IEType.OCTET_STRING, "size": 8, "description": "E-UTRAN trace ID"},
    87: {"name": "RelativeMMECapacity", "type": IEType.INTEGER, "range": (0, 255), "description": "Relative MME capacity"},
    88: {"name": "SourceMME-UE-S1AP-ID", "type": IEType.INTEGER, "range": (0, 4294967295), "description": "Source MME UE S1AP ID"},
    89: {"name": "Bearers-SubjectToStatusTransfer-Item", "type": IEType.SEQUENCE, "description": "Bearers subject to status transfer item"},
    90: {"name": "eNB-StatusTransfer-TransparentContainer", "type": IEType.OCTET_STRING, "description": "eNB status transfer transparent container"},
    91: {"name": "UE-associatedLogicalS1-ConnectionItem", "type": IEType.SEQUENCE, "description": "UE associated logical S1 connection item"},
    92: {"name": "ResetType", "type": IEType.CHOICE, "choices": ["s1-Interface", "partOfS1-Interface"], "description": "Reset type"},
    93: {"name": "UE-associatedLogicalS1-ConnectionListResAck", "type": IEType.SEQUENCE_OF, "description": "UE associated logical S1 connection list reset ack"},
    94: {"name": "E-RABToBeSwitchedULItem", "type": IEType.SEQUENCE, "description": "E-RAB to be switched UL item"},
    95: {"name": "E-RABToBeSwitchedULList", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be switched UL list"},
    96: {"name": "S-TMSI", "type": IEType.SEQUENCE, "description": "S-TMSI"},
    97: {"name": "cdma2000OneXRAND", "type": IEType.OCTET_STRING, "description": "CDMA2000 1X RAND"},
    98: {"name": "RequestType", "type": IEType.SEQUENCE, "description": "Request type"},
    99: {"name": "UE-S1AP-IDs", "type": IEType.CHOICE, "choices": ["uE-S1AP-ID-pair", "mME-UE-S1AP-ID"], "description": "UE S1AP IDs"},
    100: {"name": "EUTRAN-CGI", "type": IEType.SEQUENCE, "description": "EUTRAN CGI"},
    101: {"name": "OverloadResponse", "type": IEType.CHOICE, "choices": ["overloadAction"], "description": "Overload response"},
    102: {"name": "cdma2000OneXSRVCCInfo", "type": IEType.OCTET_STRING, "description": "CDMA2000 1X SRVCC info"},
    103: {"name": "E-RABFailedToBeReleasedList", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to be released list"},
    104: {"name": "Source-ToTarget-TransparentContainer", "type": IEType.OCTET_STRING, "description": "Source to target transparent container"},
    105: {"name": "ServedGUMMEIs", "type": IEType.SEQUENCE_OF, "description": "Served GUMMEIs"},
    106: {"name": "SubscriberProfileIDforRFP", "type": IEType.INTEGER, "range": (1, 256), "description": "Subscriber profile ID for RFP"},
    107: {"name": "UESecurityCapabilities", "type": IEType.SEQUENCE, "description": "UE security capabilities"},
    108: {"name": "CSFallbackIndicator", "type": IEType.ENUMERATED, "values": {"cs-fallback-required": 0, "cs-fallback-high-priority": 1}, "description": "CS fallback indicator"},
    109: {"name": "CNDomain", "type": IEType.ENUMERATED, "values": {"ps": 0, "cs": 1}, "description": "CN domain"},
    110: {"name": "E-RABReleasedList", "type": IEType.SEQUENCE_OF, "description": "E-RAB released list"},
    111: {"name": "MessageIdentifier", "type": IEType.BIT_STRING, "size": 16, "description": "Message identifier"},
    112: {"name": "SerialNumber", "type": IEType.BIT_STRING, "size": 16, "description": "Serial number"},
    113: {"name": "WarningAreaList", "type": IEType.CHOICE, "choices": ["cellIDList", "trackingAreaListforWarning", "emergencyAreaIDList"], "description": "Warning area list"},
    114: {"name": "RepetitionPeriod", "type": IEType.INTEGER, "range": (0, 4095), "description": "Repetition period"},
    115: {"name": "NumberofBroadcastRequest", "type": IEType.INTEGER, "range": (0, 65535), "description": "Number of broadcast request"},
    116: {"name": "WarningType", "type": IEType.OCTET_STRING, "size": 2, "description": "Warning type"},
    117: {"name": "WarningSecurityInfo", "type": IEType.OCTET_STRING, "size": 50, "description": "Warning security info"},
    118: {"name": "DataCodingScheme", "type": IEType.BIT_STRING, "size": 8, "description": "Data coding scheme"},
    119: {"name": "WarningMessageContents", "type": IEType.OCTET_STRING, "description": "Warning message contents"},
    120: {"name": "BroadcastCompletedAreaList", "type": IEType.CHOICE, "choices": ["cellID-Broadcast", "tAI-Broadcast", "emergencyAreaID-Broadcast"], "description": "Broadcast completed area list"},
    121: {"name": "Inter-SystemInformationTransferTypeEDT", "type": IEType.SEQUENCE, "description": "Inter-system information transfer type EDT"},
    122: {"name": "Inter-SystemInformationTransferTypeMDT", "type": IEType.SEQUENCE, "description": "Inter-system information transfer type MDT"},
    123: {"name": "Target-ToSource-TransparentContainer", "type": IEType.OCTET_STRING, "description": "Target to source transparent container"},
    124: {"name": "SRVCCOperationPossible", "type": IEType.ENUMERATED, "values": {"possible": 0}, "description": "SRVCC operation possible"},
    125: {"name": "SRVCCHOIndication", "type": IEType.ENUMERATED, "values": {"pSandCS": 0, "cSonly": 1}, "description": "SRVCC HO indication"},
    126: {"name": "NAS-DownlinkCount", "type": IEType.INTEGER, "range": (0, 16777215), "description": "NAS downlink count"},
    127: {"name": "CSG-Id", "type": IEType.BIT_STRING, "size": 27, "description": "CSG ID"},
    128: {"name": "CSG-IdList", "type": IEType.SEQUENCE_OF, "description": "CSG ID list"},
    129: {"name": "SONConfigurationTransferECT", "type": IEType.SEQUENCE, "description": "SON configuration transfer ECT"},
    130: {"name": "SONConfigurationTransferMCT", "type": IEType.SEQUENCE, "description": "SON configuration transfer MCT"},
    131: {"name": "TraceCollectionEntityIPAddress", "type": IEType.BIT_STRING, "description": "Trace collection entity IP address"},
    132: {"name": "MSClassmark2", "type": IEType.OCTET_STRING, "description": "MS classmark 2"},
    133: {"name": "MSClassmark3", "type": IEType.OCTET_STRING, "description": "MS classmark 3"},
    134: {"name": "RRC-Establishment-Cause", "type": IEType.ENUMERATED, "values": {"emergency": 0, "highPriorityAccess": 1, "mt-Access": 2, "mo-Signalling": 3, "mo-Data": 4}, "description": "RRC establishment cause"},
    135: {"name": "NASSecurityParametersfromE-UTRAN", "type": IEType.OCTET_STRING, "description": "NAS security parameters from E-UTRAN"},
    136: {"name": "NASSecurityParameterstoE-UTRAN", "type": IEType.OCTET_STRING, "description": "NAS security parameters to E-UTRAN"},
    137: {"name": "DefaultPagingDRX", "type": IEType.ENUMERATED, "values": {"v32": 0, "v64": 1, "v128": 2, "v256": 3}, "description": "Default paging DRX"},
    138: {"name": "Source-ToTarget-TransparentContainer-Secondary", "type": IEType.OCTET_STRING, "description": "Source to target transparent container secondary"},
    139: {"name": "Target-ToSource-TransparentContainer-Secondary", "type": IEType.OCTET_STRING, "description": "Target to source transparent container secondary"},
    140: {"name": "EUTRANRoundTripDelayEstimationInfo", "type": IEType.INTEGER, "range": (0, 2047), "description": "EUTRAN round trip delay estimation info"},
    141: {"name": "BroadcastCancelledAreaList", "type": IEType.CHOICE, "choices": ["cellID-Cancelled", "tAI-Cancelled", "emergencyAreaID-Cancelled"], "description": "Broadcast cancelled area list"},
    142: {"name": "ConcurrentWarningMessageIndicator", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "Concurrent warning message indicator"},
    143: {"name": "Data-Forwarding-Not-Possible", "type": IEType.ENUMERATED, "values": {"data-Forwarding-not-Possible": 0}, "description": "Data forwarding not possible"},
    144: {"name": "ExtendedRepetitionPeriod", "type": IEType.INTEGER, "range": (4096, 131071), "description": "Extended repetition period"},
    145: {"name": "CellAccessMode", "type": IEType.ENUMERATED, "values": {"hybrid": 0, "closed": 1}, "description": "Cell access mode"},
    146: {"name": "CSGMembershipStatus", "type": IEType.ENUMERATED, "values": {"member": 0, "not-member": 1}, "description": "CSG membership status"},
    147: {"name": "LPPa-PDU", "type": IEType.OCTET_STRING, "description": "LPPa PDU"},
    148: {"name": "Routing-ID", "type": IEType.INTEGER, "range": (0, 255), "description": "Routing ID"},
    149: {"name": "Time-Synchronisation-Info", "type": IEType.SEQUENCE, "description": "Time synchronisation info"},
    150: {"name": "PS-ServiceNotAvailable", "type": IEType.ENUMERATED, "values": {"ps-ServiceNotAvailable": 0}, "description": "PS service not available"},
    151: {"name": "PagingPriority", "type": IEType.ENUMERATED, "values": {"priolevel1": 0, "priolevel2": 1, "priolevel3": 2, "priolevel4": 3, "priolevel5": 4, "priolevel6": 5, "priolevel7": 6, "priolevel8": 7}, "description": "Paging priority"},
    152: {"name": "x2TNLConfigurationInfo", "type": IEType.SEQUENCE, "description": "X2 TNL configuration info"},
    153: {"name": "eNBX2ExtendedTransportLayerAddresses", "type": IEType.SEQUENCE_OF, "description": "eNB X2 extended transport layer addresses"},
    154: {"name": "GUMMEIList", "type": IEType.SEQUENCE_OF, "description": "GUMMEI list"},
    155: {"name": "GW-TransportLayerAddress", "type": IEType.BIT_STRING, "description": "GW transport layer address"},
    156: {"name": "Correlation-ID", "type": IEType.OCTET_STRING, "description": "Correlation ID"},
    157: {"name": "SourceMME-GUMMEI", "type": IEType.SEQUENCE, "description": "Source MME GUMMEI"},
    158: {"name": "MME-UE-S1AP-ID-2", "type": IEType.INTEGER, "range": (0, 4294967295), "description": "MME UE S1AP ID 2"},
    159: {"name": "RegisteredLAI", "type": IEType.SEQUENCE, "description": "Registered LAI"},
    160: {"name": "RelayNode-Indicator", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "Relay node indicator"},
    161: {"name": "TrafficLoadReductionIndication", "type": IEType.INTEGER, "range": (1, 99), "description": "Traffic load reduction indication"},
    162: {"name": "MDTConfiguration", "type": IEType.SEQUENCE, "description": "MDT configuration"},
    163: {"name": "MMERelaySupportIndicator", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "MME relay support indicator"},
    164: {"name": "GWContextReleaseIndication", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "GW context release indication"},
    165: {"name": "ManagementBasedMDTAllowed", "type": IEType.ENUMERATED, "values": {"allowed": 0}, "description": "Management based MDT allowed"},
    166: {"name": "PrivacyIndicator", "type": IEType.ENUMERATED, "values": {"immediate-MDT": 0, "logged-MDT": 1}, "description": "Privacy indicator"},
    167: {"name": "Time-UE-StayedInCell-EnhancedGranularity", "type": IEType.INTEGER, "range": (0, 40950), "description": "Time UE stayed in cell enhanced granularity"},
    168: {"name": "HO-Cause", "type": IEType.ENUMERATED, "values": {"handoverDesirableForRadioReason": 0, "timeCriticalHandover": 1}, "description": "HO cause"},
    169: {"name": "VoiceSupportMatchIndicator", "type": IEType.ENUMERATED, "values": {"supported": 0, "not-supported": 1}, "description": "Voice support match indicator"},
    170: {"name": "GUMMEIType", "type": IEType.ENUMERATED, "values": {"native": 0, "mapped": 1}, "description": "GUMMEI type"},
    171: {"name": "M3Configuration", "type": IEType.SEQUENCE, "description": "M3 configuration"},
    172: {"name": "M4Configuration", "type": IEType.SEQUENCE, "description": "M4 configuration"},
    173: {"name": "M5Configuration", "type": IEType.SEQUENCE, "description": "M5 configuration"},
    174: {"name": "MDT-Location-Info", "type": IEType.BIT_STRING, "size": 8, "description": "MDT location info"},
    175: {"name": "MobilityInformation", "type": IEType.BIT_STRING, "size": 32, "description": "Mobility information"},
    176: {"name": "Tunnel-Information-for-BBF", "type": IEType.SEQUENCE, "description": "Tunnel information for BBF"},
    177: {"name": "ManagementBasedMDTPLMNList", "type": IEType.SEQUENCE_OF, "description": "Management based MDT PLMN list"},
    178: {"name": "SignallingBasedMDTPLMNList", "type": IEType.SEQUENCE_OF, "description": "Signalling based MDT PLMN list"},
    179: {"name": "ULCOUNTValueExtended", "type": IEType.SEQUENCE, "description": "UL COUNT value extended"},
    180: {"name": "DLCOUNTValueExtended", "type": IEType.SEQUENCE, "description": "DL COUNT value extended"},
    181: {"name": "ReceiveStatusOfULPDCPSDUsExtended", "type": IEType.BIT_STRING, "description": "Receive status of UL PDCP SDUs extended"},
    182: {"name": "ECGIListForRestart", "type": IEType.SEQUENCE_OF, "description": "ECGI list for restart"},
    183: {"name": "SIPTO-Correlation-ID", "type": IEType.OCTET_STRING, "description": "SIPTO correlation ID"},
    184: {"name": "SIPTO-L-GW-TransportLayerAddress", "type": IEType.BIT_STRING, "description": "SIPTO L-GW transport layer address"},
    185: {"name": "TransportInformation", "type": IEType.SEQUENCE, "description": "Transport information"},
    186: {"name": "LHN-ID", "type": IEType.OCTET_STRING, "description": "LHN ID"},
    187: {"name": "AdditionalCSFallbackIndicator", "type": IEType.ENUMERATED, "values": {"additionalCSFallbackNotPreferred": 0}, "description": "Additional CS fallback indicator"},
    188: {"name": "TAIListForRestart", "type": IEType.SEQUENCE_OF, "description": "TAI list for restart"},
    189: {"name": "UserLocationInformation", "type": IEType.SEQUENCE, "description": "User location information"},
    190: {"name": "EmergencyAreaIDListForRestart", "type": IEType.SEQUENCE_OF, "description": "Emergency area ID list for restart"},
    191: {"name": "KillAllWarningMessages", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "Kill all warning messages"},
    192: {"name": "Masked-IMEISV", "type": IEType.BIT_STRING, "size": 64, "description": "Masked IMEISV"},
    193: {"name": "eNBIndirectX2TransportLayerAddresses", "type": IEType.SEQUENCE_OF, "description": "eNB indirect X2 transport layer addresses"},
    194: {"name": "uE-HistoryInformationFromTheUE", "type": IEType.OCTET_STRING, "description": "UE history information from the UE"},
    195: {"name": "ProSeAuthorized", "type": IEType.SEQUENCE, "description": "ProSe authorized"},
    196: {"name": "ExpectedUEBehaviour", "type": IEType.SEQUENCE, "description": "Expected UE behaviour"},
    197: {"name": "LoggedMBSFNMDT", "type": IEType.SEQUENCE, "description": "Logged MBSFN MDT"},
    198: {"name": "UERadioCapabilityForPaging", "type": IEType.OCTET_STRING, "description": "UE radio capability for paging"},
    199: {"name": "E-RABToBeModifiedListBearerModInd", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be modified list bearer modification indication"},
    200: {"name": "E-RABToBeModifiedItemBearerModInd", "type": IEType.SEQUENCE, "description": "E-RAB to be modified item bearer modification indication"},
    201: {"name": "E-RABNotToBeModifiedListBearerModInd", "type": IEType.SEQUENCE_OF, "description": "E-RAB not to be modified list bearer modification indication"},
    202: {"name": "E-RABNotToBeModifiedItemBearerModInd", "type": IEType.SEQUENCE, "description": "E-RAB not to be modified item bearer modification indication"},
    203: {"name": "E-RABModifyListBearerModConf", "type": IEType.SEQUENCE_OF, "description": "E-RAB modify list bearer modification confirm"},
    204: {"name": "E-RABModifyItemBearerModConf", "type": IEType.SEQUENCE, "description": "E-RAB modify item bearer modification confirm"},
    205: {"name": "E-RABFailedToModifyListBearerModConf", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to modify list bearer modification confirm"},
    206: {"name": "SON-Information-Report", "type": IEType.SEQUENCE, "description": "SON information report"},
    207: {"name": "Muting-Availability-Indication", "type": IEType.ENUMERATED, "values": {"available": 0, "unavailable": 1}, "description": "Muting availability indication"},
    208: {"name": "Muting-Pattern-Information", "type": IEType.SEQUENCE, "description": "Muting pattern information"},
    209: {"name": "Synchronisation-Information", "type": IEType.SEQUENCE, "description": "Synchronisation information"},
    210: {"name": "E-RABToBeReleasedListBearerModConf", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be released list bearer modification confirm"},
    211: {"name": "AssistanceDataForPaging", "type": IEType.SEQUENCE, "description": "Assistance data for paging"},
    212: {"name": "CellIdentifierAndCELevelForCECapableUEs", "type": IEType.SEQUENCE, "description": "Cell identifier and CE level for CE capable UEs"},
    213: {"name": "InformationOnRecommendedCellsAndENBsForPaging", "type": IEType.SEQUENCE, "description": "Information on recommended cells and eNBs for paging"},
    214: {"name": "RecommendedCellItem", "type": IEType.SEQUENCE, "description": "Recommended cell item"},
    215: {"name": "RecommendedENBItem", "type": IEType.SEQUENCE, "description": "Recommended eNB item"},
    216: {"name": "ProSeUEtoNetworkRelaying", "type": IEType.ENUMERATED, "values": {"authorized": 0, "not-authorized": 1}, "description": "ProSe UE to network relaying"},
    217: {"name": "ULCOUNTValuePDCP-SNlength18", "type": IEType.SEQUENCE, "description": "UL COUNT value PDCP SN length 18"},
    218: {"name": "DLCOUNTValuePDCP-SNlength18", "type": IEType.SEQUENCE, "description": "DL COUNT value PDCP SN length 18"},
    219: {"name": "ReceiveStatusOfULPDCPSDUsPDCP-SNlength18", "type": IEType.BIT_STRING, "description": "Receive status of UL PDCP SDUs PDCP SN length 18"},
    220: {"name": "M6Configuration", "type": IEType.SEQUENCE, "description": "M6 configuration"},
    221: {"name": "M7Configuration", "type": IEType.SEQUENCE, "description": "M7 configuration"},
    222: {"name": "PWSfailedECGIList", "type": IEType.SEQUENCE_OF, "description": "PWS failed ECGI list"},
    223: {"name": "MME-Group-ID", "type": IEType.OCTET_STRING, "size": 2, "description": "MME group ID"},
    224: {"name": "Additional-GUTI", "type": IEType.SEQUENCE, "description": "Additional GUTI"},
    225: {"name": "S1-Message", "type": IEType.OCTET_STRING, "description": "S1 message"},
    226: {"name": "CSGMembershipInfo", "type": IEType.SEQUENCE, "description": "CSG membership info"},
    227: {"name": "Paging-eDRXInformation", "type": IEType.SEQUENCE, "description": "Paging eDRX information"},
    228: {"name": "UE-RetentionInformation", "type": IEType.ENUMERATED, "values": {"ues-retained": 0}, "description": "UE retention information"},
    229: {"name": "Unknown-229", "type": IEType.OCTET_STRING, "description": "WS extension"},
    230: {"name": "UE-Usage-Type", "type": IEType.INTEGER, "range": (0, 255), "description": "UE usage type"},
    231: {"name": "extended-UEIdentityIndexValue", "type": IEType.BIT_STRING, "size": 14, "description": "Extended UE identity index value"},
    232: {"name": "RAT-Type", "type": IEType.ENUMERATED, "values": {"nbiot": 0}, "description": "RAT type"},
    233: {"name": "BearerType", "type": IEType.ENUMERATED, "values": {"non-IP": 0}, "description": "Bearer type"},
    234: {"name": "NB-IoT-DefaultPagingDRX", "type": IEType.ENUMERATED, "values": {"v128": 0, "v256": 1, "v512": 2, "v1024": 3}, "description": "NB-IoT default paging DRX"},
    235: {"name": "E-RABFailedToResumeListResumeReq", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to resume list resume request"},
    236: {"name": "E-RABFailedToResumeItemResumeReq", "type": IEType.SEQUENCE, "description": "E-RAB failed to resume item resume request"},
    237: {"name": "E-RABFailedToResumeListResumeRes", "type": IEType.SEQUENCE_OF, "description": "E-RAB failed to resume list resume response"},
    238: {"name": "E-RABFailedToResumeItemResumeRes", "type": IEType.SEQUENCE, "description": "E-RAB failed to resume item resume response"},
    239: {"name": "NB-IoT-Paging-eDRXInformation", "type": IEType.SEQUENCE, "description": "NB-IoT paging eDRX information"},
    240: {"name": "V2XServicesAuthorized", "type": IEType.SEQUENCE, "description": "V2X services authorized"},
    241: {"name": "UEUserPlaneCIoTSupportIndicator", "type": IEType.ENUMERATED, "values": {"supported": 0}, "description": "UE user plane CIoT support indicator"},
    242: {"name": "CE-mode-B-SupportIndicator", "type": IEType.ENUMERATED, "values": {"supported": 0}, "description": "CE mode B support indicator"},
    243: {"name": "SRVCCOperationNotPossible", "type": IEType.ENUMERATED, "values": {"notPossible": 0}, "description": "SRVCC operation not possible"},
    244: {"name": "NB-IoT-UEIdentityIndexValue", "type": IEType.BIT_STRING, "size": 12, "description": "NB-IoT UE identity index value"},
    245: {"name": "RRC-Resume-Cause", "type": IEType.ENUMERATED, "values": {"emergency": 0, "highPriorityAccess": 1, "mt-Access": 2, "mo-Signalling": 3, "mo-Data": 4, "mo-VoiceCall": 5, "mo-VideoCall": 6, "mo-SMS": 7}, "description": "RRC resume cause"},
    246: {"name": "DCN-ID", "type": IEType.INTEGER, "range": (0, 65535), "description": "DCN ID"},
    247: {"name": "ServedDCNs", "type": IEType.SEQUENCE_OF, "description": "Served DCNs"},
    248: {"name": "UESidelinkAggregateMaximumBitrate", "type": IEType.SEQUENCE, "description": "UE sidelink aggregate maximum bitrate"},
    249: {"name": "DLNASPDUDeliveryAckRequest", "type": IEType.ENUMERATED, "values": {"requested": 0}, "description": "DL NAS PDU delivery ack request"},
    250: {"name": "Coverage-Level", "type": IEType.INTEGER, "range": (0, 3), "description": "Coverage level"},
    251: {"name": "EnhancedCoverageRestricted", "type": IEType.ENUMERATED, "values": {"restricted": 0, "notRestricted": 1}, "description": "Enhanced coverage restricted"},
    252: {"name": "UE-Level-QoS-Parameters", "type": IEType.SEQUENCE, "description": "UE level QoS parameters"},
    253: {"name": "DL-CP-SecurityInformation", "type": IEType.SEQUENCE, "description": "DL CP security information"},
    254: {"name": "UL-CP-SecurityInformation", "type": IEType.SEQUENCE, "description": "UL CP security information"},
    255: {"name": "extended-e-RAB-MaximumBitrateDL", "type": IEType.INTEGER, "range": (10001, 4000000000), "description": "Extended e-RAB maximum bitrate DL"},
    256: {"name": "extended-e-RAB-MaximumBitrateUL", "type": IEType.INTEGER, "range": (10001, 4000000000), "description": "Extended e-RAB maximum bitrate UL"},
    257: {"name": "extended-e-RAB-GuaranteedBitrateDL", "type": IEType.INTEGER, "range": (10001, 4000000000), "description": "Extended e-RAB guaranteed bitrate DL"},
    258: {"name": "extended-e-RAB-GuaranteedBitrateUL", "type": IEType.INTEGER, "range": (10001, 4000000000), "description": "Extended e-RAB guaranteed bitrate UL"},
    259: {"name": "extended-uEaggregateMaximumBitRateDL", "type": IEType.INTEGER, "range": (10001, 4000000000), "description": "Extended UE aggregate maximum bit rate DL"},
    260: {"name": "extended-uEaggregateMaximumBitRateUL", "type": IEType.INTEGER, "range": (10001, 4000000000), "description": "Extended UE aggregate maximum bit rate UL"},
    261: {"name": "NRrestrictioninEPSasSecondaryRAT", "type": IEType.ENUMERATED, "values": {"nRrestrictedinEPSasSecondaryRAT": 0}, "description": "NR restriction in EPS as secondary RAT"},
    262: {"name": "UEAppLayerMeasConfig", "type": IEType.SEQUENCE, "description": "UE app layer measurement config"},
    263: {"name": "UE-Application-Layer-Measurement-Capability", "type": IEType.BIT_STRING, "description": "UE application layer measurement capability"},
    264: {"name": "SecondaryRATDataUsageReportList", "type": IEType.SEQUENCE_OF, "description": "Secondary RAT data usage report list"},
    265: {"name": "SecondaryRATDataUsageReportItem", "type": IEType.SEQUENCE, "description": "Secondary RAT data usage report item"},
    266: {"name": "HandoverFlag", "type": IEType.ENUMERATED, "values": {"handoverPreparation": 0}, "description": "Handover flag"},
    267: {"name": "E-RABUsageReportItem", "type": IEType.SEQUENCE, "description": "E-RAB usage report item"},
    268: {"name": "SecondaryRATDataUsageRequest", "type": IEType.ENUMERATED, "values": {"requested": 0}, "description": "Secondary RAT data usage request"},
    269: {"name": "NRUESecurityCapabilities", "type": IEType.SEQUENCE, "description": "NR UE security capabilities"},
    270: {"name": "UnlicensedSpectrumRestriction", "type": IEType.ENUMERATED, "values": {"unlicensed-restricted": 0}, "description": "Unlicensed spectrum restriction"},
    271: {"name": "CE-ModeBRestricted", "type": IEType.ENUMERATED, "values": {"restricted": 0, "notRestricted": 1}, "description": "CE mode B restricted"},
    272: {"name": "LTE-M-Indication", "type": IEType.ENUMERATED, "values": {"lte-m": 0}, "description": "LTE-M indication"},
    273: {"name": "DownlinkPacketLossRate", "type": IEType.INTEGER, "range": (0, 1000), "description": "Downlink packet loss rate"},
    274: {"name": "UplinkPacketLossRate", "type": IEType.INTEGER, "range": (0, 1000), "description": "Uplink packet loss rate"},
    275: {"name": "UECapabilityInfoRequest", "type": IEType.ENUMERATED, "values": {"requested": 0}, "description": "UE capability info request"},
    276: {"name": "serviceType", "type": IEType.ENUMERATED, "values": {"qMC-for-streaming-service": 0, "qMC-for-MTSI-service": 1}, "description": "Service type"},
    277: {"name": "AerialUEsubscriptionInformation", "type": IEType.ENUMERATED, "values": {"allowed": 0, "not-allowed": 1}, "description": "Aerial UE subscription information"},
    278: {"name": "Subscription-Based-UE-DifferentiationInfo", "type": IEType.SEQUENCE, "description": "Subscription based UE differentiation info"},
    279: {"name": "Unknown-279", "type": IEType.OCTET_STRING, "description": "WS extension"},
    280: {"name": "EndIndication", "type": IEType.ENUMERATED, "values": {"no-further-data": 0, "further-data-exists": 1}, "description": "End indication"},
    281: {"name": "EDT-Session", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "EDT session"},
    282: {"name": "CNTypeRestrictions", "type": IEType.SEQUENCE, "description": "CN type restrictions"},
    283: {"name": "PendingDataIndication", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "Pending data indication"},
    284: {"name": "BluetoothMeasurementConfiguration", "type": IEType.SEQUENCE, "description": "Bluetooth measurement configuration"},
    285: {"name": "WLANMeasurementConfiguration", "type": IEType.SEQUENCE, "description": "WLAN measurement configuration"},
    286: {"name": "WarningAreaCoordinates", "type": IEType.OCTET_STRING, "description": "Warning area coordinates"},
    287: {"name": "NRrestrictionin5GS", "type": IEType.ENUMERATED, "values": {"nRrestrictedin5GS": 0}, "description": "NR restriction in 5GS"},
    288: {"name": "PSCellInformation", "type": IEType.SEQUENCE, "description": "PS cell information"},
    289: {"name": "Unknown-289", "type": IEType.OCTET_STRING, "description": "WS extension"},
    290: {"name": "LastNG-RANPLMNIdentity", "type": IEType.OCTET_STRING, "size": 3, "description": "Last NG-RAN PLMN identity"},
    291: {"name": "ConnectedengNBList", "type": IEType.SEQUENCE_OF, "description": "Connected en-gNB list"},
    292: {"name": "ConnectedengNBToAddList", "type": IEType.SEQUENCE_OF, "description": "Connected en-gNB to add list"},
    293: {"name": "ConnectedengNBToRemoveList", "type": IEType.SEQUENCE_OF, "description": "Connected en-gNB to remove list"},
    294: {"name": "EN-DCSONConfigurationTransfer-ECT", "type": IEType.SEQUENCE, "description": "EN-DC SON configuration transfer ECT"},
    295: {"name": "EN-DCSONConfigurationTransfer-MCT", "type": IEType.SEQUENCE, "description": "EN-DC SON configuration transfer MCT"},
    296: {"name": "IMSvoiceEPSfallbackfrom5G", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "IMS voice EPS fallback from 5G"},
    297: {"name": "TimeSinceSecondaryNodeRelease", "type": IEType.INTEGER, "range": (0, 4095), "description": "Time since secondary node release"},
    298: {"name": "RequestTypeAdditionalInfo", "type": IEType.BIT_STRING, "size": 8, "description": "Request type additional info"},
    299: {"name": "AdditionalRRMPriorityIndex", "type": IEType.BIT_STRING, "size": 32, "description": "Additional RRM priority index"},
    300: {"name": "ContextatSource", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "Context at source"},
    301: {"name": "IAB-Authorized", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "IAB authorized"},
    302: {"name": "IAB-Node-Indication", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "IAB node indication"},
    303: {"name": "IAB-Supported", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "IAB supported"},
    304: {"name": "DataSize", "type": IEType.INTEGER, "range": (1, 1000), "description": "Data size"},
    305: {"name": "Ethernet-Type", "type": IEType.OCTET_STRING, "size": 2, "description": "Ethernet type"},
    306: {"name": "NRV2XServicesAuthorized", "type": IEType.SEQUENCE, "description": "NR V2X services authorized"},
    307: {"name": "NRUESidelinkAggregateMaximumBitrate", "type": IEType.SEQUENCE, "description": "NR UE sidelink aggregate maximum bitrate"},
    308: {"name": "PC5QoSParameters", "type": IEType.SEQUENCE, "description": "PC5 QoS parameters"},
    309: {"name": "IntersystemSONConfigurationTransferMCT", "type": IEType.SEQUENCE, "description": "Intersystem SON configuration transfer MCT"},
    310: {"name": "IntersystemSONConfigurationTransferECT", "type": IEType.SEQUENCE, "description": "Intersystem SON configuration transfer ECT"},
    311: {"name": "IntersystemMeasurementConfiguration", "type": IEType.SEQUENCE, "description": "Intersystem measurement configuration"},
    312: {"name": "SourceNodeID", "type": IEType.CHOICE, "choices": ["sourceenGNB-ID"], "description": "Source node ID"},
    313: {"name": "NB-IoT-RLF-Report-Container", "type": IEType.OCTET_STRING, "description": "NB-IoT RLF report container"},
    314: {"name": "UERadioCapabilityID", "type": IEType.OCTET_STRING, "description": "UE radio capability ID"},
    315: {"name": "UERadioCapability-NR-Format", "type": IEType.OCTET_STRING, "description": "UE radio capability NR format"},
    316: {"name": "MDTConfigurationNR", "type": IEType.SEQUENCE, "description": "MDT configuration NR"},
    317: {"name": "DAPSRequestInfo", "type": IEType.SEQUENCE, "description": "DAPS request info"},
    318: {"name": "DAPSResponseInfoList", "type": IEType.SEQUENCE_OF, "description": "DAPS response info list"},
    319: {"name": "DAPSResponseInfoItem", "type": IEType.SEQUENCE, "description": "DAPS response info item"},
    320: {"name": "NotifySourceeNB", "type": IEType.ENUMERATED, "values": {"notifyrecommended": 0}, "description": "Notify source eNB"},
    321: {"name": "eNB-EarlyStatusTransfer-TransparentContainer", "type": IEType.OCTET_STRING, "description": "eNB early status transfer transparent container"},
    322: {"name": "Bearers-SubjectToEarlyStatusTransfer-Item", "type": IEType.SEQUENCE, "description": "Bearers subject to early status transfer item"},
    323: {"name": "WUS-Assistance-Information", "type": IEType.SEQUENCE, "description": "WUS assistance information"},
    324: {"name": "NB-IoT-PagingDRX", "type": IEType.ENUMERATED, "values": {"v32": 0, "v64": 1, "v128": 2, "v256": 3, "v512": 4, "v1024": 5}, "description": "NB-IoT paging DRX"},
    325: {"name": "TraceCollectionEntityURI", "type": IEType.OCTET_STRING, "description": "Trace collection entity URI"},
    326: {"name": "EmergencyIndicator", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "Emergency indicator"},
    327: {"name": "UERadioCapabilityForPaging-NR-Format", "type": IEType.OCTET_STRING, "description": "UE radio capability for paging NR format"},
    328: {"name": "SourceTransportLayerAddress", "type": IEType.BIT_STRING, "description": "Source transport layer address"},
    329: {"name": "lastVisitedPSCellList", "type": IEType.SEQUENCE_OF, "description": "Last visited PS cell list"},
    330: {"name": "RACSIndication", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "RACS indication"},
    331: {"name": "PagingCause", "type": IEType.ENUMERATED, "values": {"voice": 0, "sms": 1}, "description": "Paging cause"},
    332: {"name": "SecurityIndication", "type": IEType.SEQUENCE, "description": "Security indication"},
    333: {"name": "SecurityResult", "type": IEType.SEQUENCE, "description": "Security result"},
    334: {"name": "E-RABSecurityResultItem", "type": IEType.SEQUENCE, "description": "E-RAB security result item"},
    335: {"name": "E-RABSecurityResultList", "type": IEType.SEQUENCE_OF, "description": "E-RAB security result list"},
    336: {"name": "RAT-Restrictions", "type": IEType.SEQUENCE, "description": "RAT restrictions"},
    337: {"name": "UEContextReferenceatSourceeNB", "type": IEType.OCTET_STRING, "description": "UE context reference at source eNB"},
    338: {"name": "Unknown-338", "type": IEType.OCTET_STRING, "description": "WS extension"},
    339: {"name": "LTE-NTN-TAI-Information", "type": IEType.SEQUENCE, "description": "LTE NTN TAI information"},
    340: {"name": "SourceNodeTransportLayerAddress", "type": IEType.BIT_STRING, "description": "Source node transport layer address"},
    341: {"name": "E-RABToBeUpdatedList", "type": IEType.SEQUENCE_OF, "description": "E-RAB to be updated list"},
    342: {"name": "E-RABToBeUpdatedItem", "type": IEType.SEQUENCE, "description": "E-RAB to be updated item"},
    343: {"name": "SourceSNID", "type": IEType.CHOICE, "choices": ["sourceenGNB-ID"], "description": "Source SN ID"},
    344: {"name": "LoggedMDTTrigger", "type": IEType.SEQUENCE, "description": "Logged MDT trigger"},
    345: {"name": "SensorMeasurementConfiguration", "type": IEType.SEQUENCE, "description": "Sensor measurement configuration"},
    346: {"name": "M4ReportAmount", "type": IEType.ENUMERATED, "values": {"r1": 0, "r2": 1, "r4": 2, "r8": 3, "r16": 4, "r32": 5, "r64": 6, "infinity": 7}, "description": "M4 report amount"},
    347: {"name": "M5ReportAmount", "type": IEType.ENUMERATED, "values": {"r1": 0, "r2": 1, "r4": 2, "r8": 3, "r16": 4, "r32": 5, "r64": 6, "infinity": 7}, "description": "M5 report amount"},
    348: {"name": "M6ReportAmount", "type": IEType.ENUMERATED, "values": {"r1": 0, "r2": 1, "r4": 2, "r8": 3, "r16": 4, "r32": 5, "r64": 6, "infinity": 7}, "description": "M6 report amount"},
    349: {"name": "M7ReportAmount", "type": IEType.ENUMERATED, "values": {"r1": 0, "r2": 1, "r4": 2, "r8": 3, "r16": 4, "r32": 5, "r64": 6, "infinity": 7}, "description": "M7 report amount"},
    350: {"name": "TimeBasedHandoverInformation", "type": IEType.SEQUENCE, "description": "Time based handover information"},
    351: {"name": "Bearers-SubjectToDLDiscarding-Item", "type": IEType.SEQUENCE, "description": "Bearers subject to DL discarding item"},
    352: {"name": "Bearers-SubjectToDLDiscardingList", "type": IEType.SEQUENCE_OF, "description": "Bearers subject to DL discarding list"},
    353: {"name": "CoarseUELocationRequested", "type": IEType.ENUMERATED, "values": {"true": 0}, "description": "Coarse UE location requested"},
    354: {"name": "CoarseUELocation", "type": IEType.SEQUENCE, "description": "Coarse UE location"}
}

def get_ie_definition(ie_id: int) -> Optional[Dict[str, Any]]:
    """Get IE definition by ID"""
    return S1AP_IES.get(ie_id)

def get_ie_name(ie_id: int) -> str:
    """Get IE name by ID"""
    ie_def = S1AP_IES.get(ie_id)
    return ie_def["name"] if ie_def else f"Unknown-{ie_id}"
